project:
  type: book

book:
  title: "ManagHAL"
  author:
    - name: "Martin AMIENS"
    - affiliations:
      - name: "Universit√© Paris-saclay - Master BIBS"
  date: "2024-06-16"
  chapters:
    - index.qmd
    - remerciement.qmd

bibliography: [bibliography/references.bib]

